# Generated by Django 5.2.7 on 2025-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_noticia_options_alter_noticia_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=2000),
        ),
    ]
